import assert from 'node:assert/strict';import fs from'node:fs';import{SupaChatState,menuItems}from'./state.mjs';
const s=new SupaChatState();
s.bootTick(58000);assert.equal(s.bootElapsedMs,58000,'boot must run through the full arrangement');s.bootTick(250);assert.equal(s.bootElapsedMs,58250,'boot must continue into the next loop');const skipped=new SupaChatState();skipped.bootTick(900);skipped.skipBoot();skipped.bootTick(7100);assert.equal(skipped.bootElapsedMs,900,'any key must skip remaining boot');
s.left();assert.equal(s.screen,'menu');const tone0=s.tones;s.down();assert.equal(s.menuSelection,1);assert.equal(s.tones,tone0+1,'menu navigation must tone');
s.menuSelection=2;s.enter();assert.equal(s.screen,'walkie');s.holdSpace();s.tick(1200);s.releaseSpace();assert.equal(s.clipReady,true);s.enter();assert.equal(s.replayAudible,true);
s.left();s.open('BACK TO CHAT');assert.equal(s.screen,'chat');const result=s.type('?',{shift:true});assert.equal(result,'punctuation');assert.equal(s.draft,'?','question mark must remain text, not right navigation');
const beforeNotify=s.notifications;s.receive('Papa','Dinner!');assert.equal(s.notifications,beforeNotify+1,'incoming message must notify');s.draft='mine';s.enter();assert.equal(s.notifications,beforeNotify+1,'outgoing message must not notify');
s.sync('io');assert.equal(s.network,'SYNC IO -1');assert.equal(s.transport,'OFFLINE');s.sync('ok');assert.equal(s.network,'SYNCED');
for(const item of menuItems){s.open(item);assert.ok(['chat','walkie','volume','networks','status'].includes(s.screen)||item==='SYNC NOW',`screen route ${item}`)}
const firmware=fs.readFileSync(new URL('../firmware/src/main.cpp',import.meta.url),'utf8');const capture=firmware.slice(firmware.indexOf('void captureVoice()'),firmware.indexOf('void playSamples('));
assert.match(firmware,/identity\.indexOf\("albie"\) >= 0\) return TFT_SKYBLUE/);assert.match(firmware,/identity\.indexOf\("juju"\).*identity\.indexOf\("julien"\).*return TFT_ORANGE/);assert.match(firmware,/identity\.indexOf\("papa"\) >= 0\) return TFT_GREEN/);assert.match(firmware,/participantColour\(message\.authorId, message\.authorName\)/);assert.match(firmware,/setFont\(&fonts::Font2\)/);assert.match(firmware,/lines\[index\]\.mine \? std::max\(3, 237 - display\.textWidth/);
const webApp=fs.readFileSync(new URL('../server/web/app.js',import.meta.url),'utf8');const webCss=fs.readFileSync(new URL('../server/web/controls.css',import.meta.url),'utf8');assert.match(webApp,/\['albie', 'juju', 'papa'\]/);assert.match(webCss,/--albie:#7dd3fc/);assert.match(webCss,/--julien:#ffad5c/);assert.match(webCss,/--papa:#a7f070/);
assert.match(capture,/voiceDmaQueued > 2/);assert.match(capture,/voiceDmaBlocks\[\(queuedIndex \+ 1\) % 3\]/);assert.match(firmware,/kBootTuneStepMs = 250/);assert.match(firmware,/Keyboard\.isPressed\(\) \|\| M5Cardputer\.BtnA\.isPressed\(\)/);assert.doesNotMatch(firmware,/lines\.back\(\)\.text \+= " \["/);assert.match(firmware,/messageNotificationPending = true/);assert.match(firmware,/timeKnown && initialSyncComplete/);assert.match(firmware,/client\.verify\(kTlsFingerprint, kApiHost\)/);assert.match(firmware,/walkieSocket\.beginSSL\(kApiHost, 443, "\/supachat\/walkie", kTlsFingerprint\)/);const pin=firmware.match(/kTlsFingerprint\[\] = "([0-9A-F ]+)"/)[1].replaceAll(' ','');assert.equal(pin.length,64,'ESP32 pin must be SHA-256');assert.match(firmware,/micConfig\.magnification = 48/);assert.match(firmware,/navigationChord = !\(keys\.shift \|\| keys\.ctrl/);assert.match(firmware,/menuSelection = \(menuSelection \+ 1\) % 6; playNextTone\(\)/);assert.match(firmware,/kEspNowEnabled = false/);
console.log('supachat_emulator_flow=PASS');
