import{SupaChatState,menuPages,networks}from'./state.mjs';
const s=new SupaChatState(),c=document.querySelector('#screen'),x=c.getContext('2d');x.imageSmoothingEnabled=false;
window.supachatState=s;
const C={black:'#000',white:'#fff',green:'#62e86f',albie:'#7dd3fc',juju:'#ffad5c',papa:'#a7f070',yellow:'#ffd83d',red:'#ff4747',grey:'#59615d',dark:'#26302b',header:'#123b27'};
function rect(a,b,w,h,color,r=0){x.fillStyle=color;r?round(a,b,w,h,r):x.fillRect(a,b,w,h)}function round(a,b,w,h,r){x.beginPath();x.roundRect(a,b,w,h,r);x.fill()}
function text(v,a,b,color=C.white,size=8){x.fillStyle=color;x.font=`${size}px "Courier New",monospace`;x.textBaseline='top';x.fillText(String(v),a,b)}
function header(title){rect(0,0,240,20,C.header);text(title,5,6);if(title==='FAMLY')text(s.easternTime||'--:--',40,6);text(s.network.slice(0,10),106,6,s.network==='SYNCED'?C.white:C.yellow);const b=`${s.batteryLevel<0?'?':s.batteryLevel}%`;text(b,237-b.length*9,4,C.white,12);if(s.externalPowerDetected){x.fillStyle=C.yellow;x.beginPath();x.moveTo(199,2);x.lineTo(194,10);x.lineTo(199,10);x.lineTo(197,8);x.lineTo(203,8);x.lineTo(196,18);x.fill()}}
function chat(){header('');const left=(s.roomSelection-1+s.rooms.length)%s.rooms.length,right=(s.roomSelection+1)%s.rooms.length,title=s.currentRoom.slice(0,10);text(s.roomNew[left]?'<*':'< ',4,6,s.roomNew[left]?C.yellow:C.grey);text(title,50-title.length*3,6);text(s.roomNew[right]?'*>':' >',91,6,s.roomNew[right]?C.yellow:C.grey);let lines=[];for(const m of s.messages){const mine=m.author===s.name;if(!mine)lines.push({v:m.author.slice(0,5),id:m.id,mine:false,label:true});if(m.replyTo)lines.push({v:`reply #${m.replyTo}`,id:'grey',mine,label:true});let value=m.deleted?'[deleted]':m.voice?'[voice message]':m.body;if(m.edited)value+=' [edit]';if(m.reactions)value+=` [+${m.reactions}]`;while(value){let split=value.length<=25?value.length:value.lastIndexOf(' ',25);if(split<6)split=Math.min(25,value.length);lines.push({v:value.slice(0,split),id:m.id,mine,label:false});value=value.slice(split).replace(/^ +/,'')}}let first=lines.length,used=0;while(first>0){const h=lines[first-1].label?10:17;if(used+h>82)break;used+=h;first--}let y=24;for(const l of lines.slice(first)){const size=l.label?8:13;x.font=`${size}px "Courier New",monospace`;const px=l.mine?Math.max(3,237-x.measureText(l.v).width):3;text(l.v,px,y,C[l.id]||C.white,size);y+=l.label?10:17}rect(0,106,240,1,C.grey);text('> ',3,112,C.yellow);text(s.draft.slice(-34),15,112);const duelLine=s.duel?.status==='active'?(s.duel.choice?'DUEL LOCKED - OPEN MENU':'DUEL READY - OPEN MENU'):s.duel?.status==='pending'?(s.duel.challengedByMe?'DUEL WAITING - OPEN MENU':'DUEL CHALLENGE - MENU'):s.duel?'DUEL RESULT - OPEN MENU':(s.typingNotice||'');text(duelLine,3,126,C.grey);text(`${s.draft.length}/140`,198,126,C.grey)}
function menu(){header(s.menuPage?'MENU DEVICE':'MENU COMMS');menuPages[s.menuPage].forEach((m,i)=>{const y=25+i*20,sel=i===s.menuSelection;rect(6,y,228,17,sel?C.green:C.dark,4);text(m,13,y+5,sel?C.black:C.white);if(!s.menuPage&&i===2&&s.duelAttention)text('*',220,y+5,sel?C.black:C.yellow)});text(`< PAGE  ${s.menuPage+1}/2  PAGE >   ENTER`,6,117,C.grey)}
function arrow(cx,cy,d,color){x.fillStyle=color;x.beginPath();if(d===0){x.moveTo(cx,cy-4);x.lineTo(cx-4,cy+3);x.lineTo(cx+4,cy+3)}else if(d===1){x.moveTo(cx+4,cy);x.lineTo(cx-3,cy-4);x.lineTo(cx-3,cy+4)}else if(d===2){x.moveTo(cx,cy+4);x.lineTo(cx-4,cy-3);x.lineTo(cx+4,cy-3)}else{x.moveTo(cx-4,cy);x.lineTo(cx+3,cy-4);x.lineTo(cx+3,cy+4)}x.fill()}
function duelOption(a,b,w,before,after,d,selected){rect(a,b,w,18,selected?C.green:C.dark,5);const fg=selected?C.black:C.white,content=(before.length+after.length)*6+12,start=a+(w-content)/2;text(before,start,b+5,fg);const ax=start+before.length*6+5;arrow(ax,b+9,d,fg);text(after,ax+7,b+5,fg)}
function duel(){header('DUEL');if(!s.duel){text(`CHALLENGE · ${s.currentRoom}`.slice(0,36),6,25,C.yellow);s.duelists.forEach((p,i)=>{const y=39+i*17,sel=i===s.duelOpponentSelection;rect(6,y,228,15,sel?C.green:C.dark,4);text(`${p.name.padEnd(20)} ${p.status}`,12,y+4,sel?C.black:C[p.id]||C.white)});text('UP/DOWN CHOOSE  ENTER DUEL',6,123,C.grey);return}text(`${s.duel.score[0]}  -  ${s.duel.score[1]}`,94,22);if(s.duel.status==='pending'){x.strokeStyle=Math.floor(Date.now()/280)%2?C.juju:C.grey;x.lineWidth=1;x.strokeRect(8,37,224,56);text(`${s.duel.challenger.slice(0,13)}  VS  ${s.duel.opponent.slice(0,13)}`,18,48,C.yellow);text(s.duel.challengedByMe?'WAITING FOR ANSWER':'YOU ARE CHALLENGED',s.duel.challengedByMe?65:54,72,C.white);text(s.duel.challengedByMe?'DEL CANCEL        MENU BACK':'ENTER ACCEPT  DEL DECLINE',6,117,C.grey);return}if(s.duel.status==='active'){if(s.duel.choice){text('SPELL LOCKED',48,52,C.green,16);text('WAITING FOR RIVAL',59,80,C.grey);const f=Math.floor(Date.now()/70)%12;rect(111+(f<6?f:12-f)*3,99,6,6,C.juju,3);text('MENU BACK · RESULT AUTOPLAYS',6,123,C.grey);return}duelOption(84,27,72,'PRO','TEGO',0,s.duelSelection===0);duelOption(4,57,83,'LEVI','CORP',3,s.duelSelection===3);duelOption(153,57,82,'SEC','TUM',1,s.duelSelection===1);duelOption(82,87,78,'LANG','LOCK',2,s.duelSelection===2);text(s.duelSelection<0?'ARROWS CHOOSE · ENTER CAST':'ENTER CAST · ARROWS CHANGE',6,117,s.duelSelection<0?C.grey:C.yellow);return}const complete=s.duel.status==='complete',won=complete&&s.duel.won,color=complete?(won?C.green:C.red):C.yellow,label=complete?(won?'VICTORY':'DEFEAT'):s.duel.status.toUpperCase();text(label,120-label.length*9,48,color,24);text(`FINAL ${s.duel.score[0]} - ${s.duel.score[1]}`,82,84);text('ENTER DONE          MENU BACK',6,120,C.grey)}
function rooms(){header('ROOMS');s.rooms.forEach((m,i)=>{const y=22+i*15,sel=i===s.roomSelection;rect(6,y,228,13,sel?C.green:C.dark,3);text(m,12,y+3,sel?C.black:C.white)});text('UP/DOWN CHOOSE    ENTER OPEN',6,123,C.grey)}
function walkie(){header('VOICE');if(s.recording){text('RECORDING',12,32,C.red,16);text(`${(s.recordedMs/1000).toFixed(1)}s / 30s`,12,62)}else{const clips=s.messages.filter(m=>m.voice).reverse();clips.slice(Math.max(0,s.voiceSelection-3),Math.max(0,s.voiceSelection-3)+4).forEach((m,row)=>{const index=Math.max(0,s.voiceSelection-3)+row,selected=index===s.voiceSelection,y=23+row*17;rect(5,y,230,15,selected?C.green:C.dark,3);text(`${m.author.slice(0,5).padEnd(5)}  voice #${m.messageId}`,9,y+4,selected?C.black:C[m.id]||C.white)});text(s.walkie.slice(0,35),7,94,C.yellow)}text('UP/DOWN CHOOSE  ENTER PLAY/STOP',6,111,C.grey);text('HOLD SPACE RECORD   LEFT MENU',6,123,C.grey)}
function volume(){header('VOLUME');text(['MUTE','LOW','MEDIUM','HIGH','MAX'][s.volume],72,39,C.yellow,16);for(let i=0;i<5;i++)rect(20+i*42,72,30,20,i<=s.volume&&s.volume?C.green:C.dark,4);text('LEFT/RIGHT CHANGE   OK BACK',6,116,C.grey)}
function status(){header('STATUS');[['NODE',s.name],['WIFI',s.ssid||'offline'],['STATE',s.network],['TIME','known'],['BATTERY',`${s.batteryLevel}%  ${s.batteryVoltageMv} mV`],['POWER',s.externalPowerDetected?'cable detected':'not detected'],['SD/KEY','ready / ready'],['HTTP/HEAP',`${s.http} / ${s.heap}`]].forEach((r,i)=>text(`${r[0].padEnd(10)}${r[1]}`,6,29+i*10));text('LEFT / OK  BACK',6,123,C.grey)}
function networkList(){header('NETWORKS');networks.forEach((n,i)=>{const y=23+i*16,sel=i===s.networkSelection;rect(3,y,234,14,sel?C.green:C.black);text(`${n.open?' ':'*'} ${n.ssid.slice(0,22).padEnd(22)} ${n.rssi}`,6,y+3,sel?C.black:C.white)});text('ARROWS  OK JOIN  LEFT BACK',6,121,C.grey)}
function password(){header('JOIN WIFI');text(s.selectedSsid.slice(0,28),6,28,C.yellow);text('PASSWORD',6,52);rect(5,65,230,24,C.dark,4);text(s.password.slice(-28),10,73);text(s.network.slice(0,34),6,104,C.grey);text('TYPE  ENTER JOIN  LEFT CANCEL',6,121,C.grey)}
function draw(){rect(0,0,240,135,C.black);({chat,menu,duel,rooms,walkie,volume,status,networks:networkList,password}[s.screen]||status)();leftButton.textContent=s.screen==='menu'?'◀ PAGE':s.screen==='duel'?'← SPELL':'← ROOM';rightButton.textContent=s.screen==='menu'?'PAGE ▶':s.screen==='duel'?'SPELL →':'ROOM →';document.querySelector('#state').textContent=JSON.stringify(s);document.querySelector('#tone-count').textContent=s.tones}
window.renderSupachat=draw;
let audio;function beep(){if(!s.volume)return;audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=440+(s.tones%8)*35;g.gain.value=.05;o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.12)}
function act(fn){const before=s.tones;fn();if(s.tones>before)beep();draw()}
const keyboard=document.querySelector('.keyboard'),leftButton=document.querySelector('[data-key="LEFT"]'),rightButton=document.querySelector('[data-key="RIGHT"]');leftButton.textContent='← ROOM';rightButton.textContent='ROOM →';const menuButton=document.createElement('button');menuButton.dataset.key='MENU';menuButton.textContent='REAR · MENU';keyboard.prepend(menuButton);
document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>act(()=>({MENU:()=>s.menu(),LEFT:()=>s.left(),RIGHT:()=>s.right(),UP:()=>s.up(),DOWN:()=>s.down(),ENTER:()=>s.enter(),QUESTION:()=>s.type('?',{shift:true}),BACKSPACE:()=>s.backspace()}[b.dataset.key]?.())));
document.querySelector('#text-entry').oninput=e=>{act(()=>s.type(e.target.value));e.target.value=''};
const space=document.querySelector('#space');space.onpointerdown=e=>{space.setPointerCapture(e.pointerId);s.holdSpace();draw()};space.onpointerup=space.onpointercancel=()=>{s.releaseSpace();draw()};
document.querySelector('#sync-result').onchange=e=>{s.sync(e.target.value);draw()};
window.addEventListener('keydown',e=>{if(e.code==='Space'&&s.screen==='walkie'&&!e.repeat){e.preventDefault();s.holdSpace();draw()}else if(e.key==='?'&&!e.repeat){e.preventDefault();act(()=>s.type('?',{shift:true}))}});window.addEventListener('keyup',e=>{if(e.code==='Space'){s.releaseSpace();draw()}});
setInterval(()=>{s.tick(100);if(s.recording||s.screen==='duel')draw()},100);draw();
